Check for bash existence instead of only mentioning it in a comment

diff --git a/core/src/test/resources/internal-port-check-dockerfile/Dockerfile-nc b/core/src/test/resources/internal-port-check-dockerfile/Dockerfile-nc
--- a/core/src/test/resources/internal-port-check-dockerfile/Dockerfile-nc
+++ b/core/src/test/resources/internal-port-check-dockerfile/Dockerfile-nc
@@ -1,5 +1,7 @@
-# If you ever upgrade this image, watch out for bash being installed by default in newer alpine base images
 FROM nginx:1.17-alpine
+
+# If this fails, you ended up using a base image with bash installed. Consider removing /bin/bash in this case
+RUN if bash -c true &> /dev/null; then exit 1; fi
 
 # Make sure the /proc/net/tcp* check fails in this container
 RUN rm /usr/bin/awk
